### ISSUE TITLE
Load does not add up as expected

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#10]
![ivy](https://cloud.githubusercontent.com/assets/1303760/5921015/134b420a-a641-11e4-8a9c-6550ff3e21b4.png)
I would expect load of the top node to be the sum of the load on the child nodes.

**Comment by antw** [comment]
Closing since since is solved with the new calculator.

FYI the values did add up since "office" and "home" had local production which provided some of their energy, although this isn't obvious in the diagram. LV#2 was 5.1 since that's how much *extra* it had to provide to meet the demand of its two child nodes.

**Comment by ChaelKruip** [comment]
> FYI

TY :+1:
