### ISSUE TITLE
It is very easy to edit existing testing grounds (even those that I did not create myself)

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etloader#105]
I opened http://ivy.et-engine.com/testing_grounds/44 (which was created by @ChaelKruip ) and started editing without realising that I was actually overwriting @ChaelKruip 's testing ground. I think the user should at least be warned that this is happening.

ps: I have already apologised to @ChaelKruip ;)

**Comment by grdw** [comment]
Right now a testing ground does not belong to a specific user. 

This is done on purpose, due to the fact that users were introduced later on in the application. So it's 'difficult' to determine which existing testing grounds belong to which registered users. 

For that matter, @ChaelKruip: when this issue is being fixed, is it okay if I assign all testing grounds to you, and that you distribute the testing grounds to the correct users?

**Comment by ChaelKruip** [comment]
> is it okay if I assign all testing grounds to you, and that you distribute the testing grounds to the correct users?

:+1:

**Comment by grdw** [comment]
A testing ground now belongs to a user :) in fact all testing grounds belong to you, @ChaelKruip. Maybe you could give the testing grounds to the correct users.
