### ISSUE TITLE
Why do I see discrepancies between the load chart and the load profile?

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etloader#111]
I have created a testing ground with only one technology, an electric vehicle, connected. I assigned a profile to it and was expecting the load chart to look exactly the same as this profile. However, they look very different and there is also negative load that I hadn't expected.
 
Do you know why this is happening, @antw?

**Load chart**

![screen shot 2015-05-13 at 12 14 35](https://cloud.githubusercontent.com/assets/4669028/7608442/eb7b5cca-f969-11e4-90b4-b862eee4c2e2.png)

**Load profile**

![screen shot 2015-05-13 at 12 15 03](https://cloud.githubusercontent.com/assets/4669028/7608444/ef06749c-f969-11e4-8c3b-e68da8c6b906.png)

**Comment by antw** [comment]
I think I understand what's going on here. The negatives are almost certainly a bug which I'm still checking out, but I have a question first: in this example, what do you think is the total storage capacity of the vehicle?

**Comment by ChaelKruip** [comment]
> in this example, what do you think is the total storage capacity of the vehicle

I think the **volume** (in kWh) for EV is 25kWh as specified in https://github.com/quintel/etdataset/issues/597#issuecomment-98846395.

**Comment by jorisberkhout** [comment]
> I think the volume (in kWh) for EV is 25kWh as specified in quintel/etdataset#597 (comment).

Correct, but I don't think this is relevant for the above profiles, since I used the *load* profiles for an electric vehicle and not the *availability* profiles (which are net on Ivy).

**Comment by ChaelKruip** [comment]
>  I used the load profiles for an electric vehicle and not the availability profiles (which are not yet on Ivy).

Good point @jorisberkhout. Thanks for clarifying!

**Comment by antw** [comment]
I'm still looking into the negatives. The "spikes" in the EV load are, I think, more easily explained.

* `capacity` is currently not a supported attribute of storage technologies. It *will* be soon – presumably mapping to `input_capacity` – but at moment the behaviour of storage when you set this attribute is "undefined" (i.e. probably broken). If you set a `capacity`, I think you'll trigger [the use of a capacity-scaled curve](https://github.com/quintel/etloader/blob/e43e9be62937d05f6e8286ab19b2af46ffe91c6e/app/models/installed_technology.rb#L61-L62) instead of using the raw curve.

  Until `input_capacity` is added for storage technologies, it is assumed to be infinite (if there is sufficient excess in the network, the storage can charge to its full capacity in one time-step).

* Storage technologies require a `storage` attribute which defines their volume. The new front-end form does not provide this attribute.

* ev_profile_11_3.3_kW.csv appears to contain raw kW values. That contradicts [this post](https://github.com/quintel/etdataset/issues/597#issuecomment-97725610) which suggests they would contain the minimum percentage (or fraction) of the battery which should be charged at each point in time.

  > positive: The EV is connected to an outlet and needs to be partially charged to make the imminent next trip. The positive value indicates the minimal percentage of the battery that needs to be charged in order to have enough charge to make the next trip (I assumed a battery volume of 25 kWh)

  I thought these were going to be "availability" curves, so a a value of 0 means the battery can be empty, 0.5 means it must be 50% full, and so on. Have I misunderstood?

**Comment by jorisberkhout** [comment]
Good points, @antw . 

> I thought these were going to be "availability" curves, so a a value of 0 means the battery can be empty, 0.5 means it must be 50% full, and so on. Have I misunderstood?

We currently have two sets of profiles for electric vehicles:
1. The *load* profiles that we created a while ago. These profiles describe the load that electric vehicles add to the network and contain raw **kW** values
2. The new set of *availability* profiles that are described in https://github.com/quintel/etdataset/issues/597#issuecomment-97725610. These indeed describe the minimum percentage of the battery that should be charged.

So far only the *load* profiles are on Ivy.

**Comment by antw** [comment]
> since I used the load profiles for an electric vehicle 

It sounds a lot like you're treating the EV as a normal technology (with a capacity and load profile) and not a storage technology. Change the car technology "type" to `generic` and you'll see a load curve which matches the profile exactly.

But, if you do that, the car won't store any excess production from within the network.

**Comment by jorisberkhout** [comment]
> It sounds a lot like you're treating the EV as a normal technology (with a capacity and load profile) and not a storage technology. Change the car technology "type" to generic and you'll see a load curve which matches the profile exactly.

Thanks for clarifying that @antw, I wasn't aware of this. @ChaelKruip pointed out that at some point he wants the user to be able to toggle between a storage / demand shifting mode and a mode without these features.

I will upload the *availability* profiles to Ivy and test again with these profiles.

Closing this issue.
