### ISSUE TITLE
Load chart is loading very slowly (sorry for that wording)

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#128]
It seems that the load chart takes forever to "pop up" for larger testing grounds. Is this due to recent changes related to storage?

**Comment by antw** [comment]
> Is this due to recent changes related to storage?

Yes and no.

Storage itself is not the reason; however, showing the "storage off" load  on the chart *is*. We have to calculate the testing ground a second time in order to compute the loads of each component when storage technologies are disabled. Instead of doing this when the page first loads – which would double the time you're looking at "Calculating your testing ground" – the "storage off" loads are calculated the first time you *want* that data. This just happens to be the first time you open a chart.

In the short-term we can improve the user experience by showing "Loading your chart..."; in the longer term, once we can store/cache *calculated* testing grounds, we could calculate "storage off" in the background, instead of waiting for the user to request the data. That would reduce the delay considerably.

**Comment by ChaelKruip** [comment]
@antw thanks for clearing that up! 

I think we could also include a toggle button for storage in the "load-chart page" that is 'off' on default. If the user decides to use storage, he/she will not mind waiting a bit longer I think...

**Comment by antw** [comment]
Fixed by 06c824ec.
