### ISSUE TITLE
EV profiles should not give negative load (discharge) if storage is 'off'

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#133]
Strangely enough, it seems that EV even shows this behaviour if the 'normal' (not the availability profiles) are used:
![ivy](https://cloud.githubusercontent.com/assets/1303760/7676122/e05a4272-fd40-11e4-97a0-f0a068c61fae.png)

**Comment by antw** [comment]
This is caused by using the *load* profiles with the EV technology. I have changed Beta to always select availability profiles – since they may be used when storage is on and off – which will resolve the problem for now.

The swing to negative load is caused by a **temporary** limitation in the calculator. It was already on my radar to be fixed but I'll make sure it gets dealt with this week. It will not be an issue when using the availability profiles.

**Comment by ChaelKruip** [comment]
Thanks for clearing that up @antw that is a big relief :smile:

**Comment by ChaelKruip** [comment]
It looks like they are still selected...

**Comment by ChaelKruip** [comment]
Closing.
