### ISSUE TITLE
Load chart should show a continuous line fore the whole year if only a fixed load is defined

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#21]
Now it scales the window vertically but nothing is plotted:
![ivy](https://cloud.githubusercontent.com/assets/1303760/6507124/3cc1761e-c350-11e4-93eb-d6858e014443.png)

**Comment by antw** [comment]
Actually, there is a single data-point being plotted; on that chart, `-5` is plotted in time-step `0`. The reason for there being no line is that the default testing ground has no technologies which use a curve. If you set even one technology to use a curve, all the "fixed-load" technologies will show a line:

![screen shot 2015-03-05 at 15 12 38](https://cloud.githubusercontent.com/assets/4383/6507472/14a2bd2e-c34a-11e4-865e-b6fe93747a1e.png)

_(Still, this issue is valid, and I'll fix it; just wanted to explain why it happens)._

**Comment by ChaelKruip** [comment]
> (Still, this issue is valid, and I'll fix it; just wanted to explain why it happens)

:+1:
