### ISSUE TITLE
When 'editing' a load curve, there is no way to specify a file to upload

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#23]
![ivy](https://cloud.githubusercontent.com/assets/1303760/6576746/82cb5250-c739-11e4-8de3-224fb4653ef1.png)

Or am I missing the point here @antw?

**Comment by antw** [comment]
> Or am I missing the point here @antw?

Yes and no. If you create a *new* curve, you will be able to replace it at a later date by uploading a new file.

The curves I have uploaded are currently "locked" to prevent them from being modified by a user. I anticipate us locking our library of profiles so that an end-user cannot affect other people's scenarios; they will still be free to upload and modify their own as they see fit.

If you'd like, I can unlock these profiles so that you may edit them.

**Comment by ChaelKruip** [comment]
> The curves I have uploaded are currently "locked" to prevent them from being modified by a user.

:+1: 

> they will still be free to upload and modify their own as they see fit.

Are we keeping track of 'owners' of profiles then? Can all users see/download all profiles but only 'owners' edit their own?

> If you'd like, I can unlock these profiles so that you may edit them.

Not for the moment. Although an 'admin' probably should be able to at some point (but that could be done by command line IMO).

**Comment by antw** [comment]
> Are we keeping track of 'owners' of profiles then? Can all users see/download all profiles but only 'owners' edit their own?

I haven't added user accounts yet, so there's no way to track who created what. All *new* uploaded profiles are created unlocked and can be modified later. The feature exists so we can differentiate between profiles *we* (QI) added – which should not be modified – and those uploaded by a user.

I expect we'll want to extend this if/when we add user accounts.

**Comment by ChaelKruip** [comment]
> I expect we'll want to extend this if/when we add user accounts.

Sounds good to me. It would be a bit annoying if others could just mess up your profile (without you knowing) and thus affect the results of your testing ground.
