### ISSUE TITLE
Calculation for single 'point' does not work anymore

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#39]
Selecting a point and clicking 'view' does not show any new information
![ivy](https://cloud.githubusercontent.com/assets/1303760/6667245/1580d15a-cbeb-11e4-9807-4eab97fb5cac.png)

Suggestion: we could show the value of the load for all the nodes in the graph for the selected point.

**Comment by ChaelKruip** [comment]
Perhaps we should just hide this button for the moment.

**Comment by ChaelKruip** [comment]
Re-assigning to @dennisschoenmakers so he can shine his light on this and find someone to make this happen.

**Comment by antw** [comment]
I would suggest hiding the button. The ability to display loads for a single point came from when we were only calculating a single time step, rather than the entire year. Even though all the load data *is* available to the front-end, and the feature could be added back in, I'm not sure how much value there is in displaying loads for a single point.

If the client does want this feature, I think we should add it to a future sprint.
