### ISSUE TITLE
Number of houses does not seem to be correct when creating testing ground scenario from saved scenario

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#42]
I created [this scaled scenario containing 110 households](http://beta.pro.et-model.com/scenarios/404772) and combined it with the 'Lochem topology' (Testing ground March 11, 2015 15:17).

The resulting testing ground contains 128 households for which technologies are specified:
![ivy](https://cloud.githubusercontent.com/assets/1303760/6776935/08a4e53e-d145-11e4-8ac5-2855c1b330a5.png)

**Comment by antw** [comment]
This is because the testing ground defines 207 connections and importing a scenario from ETEngine, as it is today, will try to assign technologies fairly between all connections.

This will be resolved once [this Trello card](https://trello.com/c/2nJXblHi/46-4-profiles-should-be-associated-to-the-end-points-of-the-network-with-some-intelligence-by-the-computer) is complete.

**Comment by ChaelKruip** [comment]
> This will be resolved once this Trello card is complete.

:+1:
