### ISSUE TITLE
Chart could use more space...

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etloader#56]
All this unused white space left an right:

![image](https://cloud.githubusercontent.com/assets/104830/6980094/181baae2-d9ed-11e4-992a-af5ef6e18b4e.png)

**Comment by grdw** [comment]
![screen shot 2015-04-22 at 1 41 00 pm](https://cloud.githubusercontent.com/assets/2676542/7273562/420f7b50-e8f5-11e4-98dd-26e89b623187.png)

I have now scaled it down to 500px. You need to drag if you want to go to the top of the topology. Scrolling seems more natural but that's kind of a hassle due to `svg`.

**Comment by ChaelKruip** [comment]
:+1:
