### ISSUE TITLE
EV batteries should be described by a profile

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#66]
The EV battery is only connected if the car is at home. Moreover, the availability of the battery for discharging (and demand shifting) is related to when the car is expected to drive.

In the following example, an EV is used for driving from 8AM to 6PM. The rest of the day, it is connected to the loading system. The user has specified that the battery should at least contain 25% of its charge for emergency drives. Also, the battery need not to be filled more than 75% at the time of departure as this is more than sufficient for the commute.

We could describe the above scenario with a curve that describes for every 15 minute interval of the year which percentage of the EV battery should be filled:
![20141209_topology_interface_v1_key](https://cloud.githubusercontent.com/assets/1303760/7067765/21113b54-dece-11e4-9e0e-9aa7a56e75a8.png)
The remainder of the battery can be used as 'flexibility' to stabilise the network or store/deliver electricity from solar PV.

The logic for the EV 'object' could be that it checks for each time step if the EV is charged at least as far as prescribed by the profile. If not, it will charge regardless of external stimuli (perhaps even breaking the network). If yes, the remaining portion of the battery is available for storing/delivering excess (or other) electricity.

**Comment by ChaelKruip** [comment]
@antw @dennisschoenmakers let me know if this is not a faithful description of our ideas as discussed earlier today.

Including @jorisberkhout @AlexanderWirtz to check that this approach makes sense to them as well.

**Comment by ChaelKruip** [comment]
After some discussion with @jorisberkhout I suggest to code two things in the same profile:
1. what fraction of the battery should be filled / charged (positive values between 0 and 1)
2. if the battery is connected to the network (-1 if not connected)

This would result in profiles like this:
![20141209_topology_interface_v1_key](https://cloud.githubusercontent.com/assets/1303760/7369006/43b2dce6-edae-11e4-8c29-1bbf2d78c1b6.png)

This approach has some advantages:
* No need for multiple profiles (less chance of combining incompatible profiles etc.)
* Easy to interpret
* Fixed format: values are always between -1 and 1 (this would not be the case if we put the kWh's of electricity in the battery in the profile)

**Comment by antw** [comment]
> 2. if the battery is connected to the network (-1 if not connected)

That's a *nice* solution; I like that. :smiley:

**Comment by jorisberkhout** [comment]
A first iteration of these profiles are available on the Dropbox (see https://github.com/quintel/etdataset/issues/597).

**Comment by ChaelKruip** [comment]
> That's a nice solution; I like that. :smiley:

Now I know why that sounded so familiar!
![nice_boulder](https://cloud.githubusercontent.com/assets/1303760/7386308/7bce654c-ee52-11e4-8aac-f3f54369d0ff.png)

**Comment by antw** [comment]
This has been implemented as of last Friday, and [an example sceanrio](http://ivy.et-engine.com/testing_grounds/45) published.

The scenario shows a producer providing a constant 2.5 kWh to the network, and an electric vehicle whose battery can store 10 kWh. In the first four frames (time-steps), the EV profile specifies that the minimum load is 25% → 50% → 75% → 100%. The load drawn by the EV is therefore 2.5 in each of those four time steps (minimum load increases by 0.25 in each frame, `0.25 * 10 = 2.5`).

The car is disconnected for two frames (time-steps 4 and 5) and then reconnects. In the final two frames (6 and 7) the EV minimum load is 50% → 100%. The producer can only satisfy half of this demand, so the rest is pulled from the grid.

Here's how the two technologies look from above: (the line smoothing makes this harder to read than it should be, see #72)

![screen shot 2015-05-06 at 16 02 03](https://cloud.githubusercontent.com/assets/4383/7496130/40451e2c-f40a-11e4-973a-1d4986667899.png)

--

I had a thought: if the car is disconnected while storing *more* energy than the minimum load profile specifies, what should happen to the excess? For example, in [the chart above](https://github.com/quintel/etloader/issues/66#issuecomment-97035443), imagine the car is disconnected at 08:00 100% charged, instead of 75%.

Currently, when the car reconnects, it does so with *zero* energy stored. It is assumes that the full amount stored is used up during the disconnection.

My view is the curve describes the amount of energy required to satisfy the needs of the car during the next period of disconnection. Therefore, any excess should be restored when the car is reconnected. In my example, the car would reconnect with 25% stored, 75% having been used during the disconnection.

**Comment by ChaelKruip** [comment]
> This has been implemented as of last Friday, and an example sceanrio published.

:+1: Super!

> It is assumes that the full amount stored is used up during the disconnection.

Well spotted @antw! I have been thinking about this for a while now. I think for now we could assume that it always returns empty (easiest). But in the future it could be nice if the car still carries the extra charge when it is reconnected. @antw any idea how difficult that would be to implement?

**Comment by antw** [comment]
> But in the future it could be nice if the car still carries the extra charge when it is reconnected. @antw any idea how difficult that would be to implement?

There would be a (small?) performance penalty in having to detect the reconnection and work out how much would still be stored at that moment-in-time, but it wouldn't be *difficult* to implement.

**Comment by jorisberkhout** [comment]
> My view is the curve describes the amount of energy required to satisfy the needs of the car during the next period of disconnection. Therefore, any excess should be restored when the car is reconnected. In my example, the car would reconnect with 25% stored, 75% having been used during the disconnection.

Good point, @antw. Like you say, the curve already (implicitly) contains information on the energy required to satisfy the needs of the car during the next period of disconnection. I have made this more explicit in a next iteration of the curves (see https://github.com/quintel/etdataset/issues/597#issuecomment-97725610). Let me know if this is useful.

**Comment by ChaelKruip** [comment]
Closing.
