### ISSUE TITLE
Title of scenario (both national and scaled) should be shown instead of ID or empty space

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#95]
![ivy](https://cloud.githubusercontent.com/assets/1303760/7513275/2f9b9e94-f4b3-11e4-94ce-6dba2a9953bc.png)

**Comment by grdw** [comment]
I did found out how to find all national scenarios
![screen shot 2015-05-07 at 2 44 15 pm](https://cloud.githubusercontent.com/assets/2676542/7515479/8f1a00ae-f4c7-11e4-84f4-ddb59c9941f6.png)

:+1: 

Although, finding the 'scaled scenarios' is going to be a bit more complicated. Either you want the scaled scenario of the selected national scenario or you want *all* the scaled scenarios, or all *your* scaled scenarios

Either way, etengine needs some changes in it's api. Currently I can only ask a batch of scenarios, but not someone's scenarios or all scenarios for that matter.

**Comment by antw** [comment]
> Either way, etengine needs some changes in it's api. Currently I can only ask a batch of scenarios, but not someone's scenarios or all scenarios for that matter.

How about an action where you can request all scenarios with a particular `preset_scenario_id`? Something like:

 ```ruby
GET /api/v3/scenarios/123/descendants

[ {
  "id": 1,
  "title": "Scenario One",
  "preset_scenario_id": 123,
  ...
}, {
  "id": 2,
  "title": "Scenario Two",
  "preset_scenario_id": 123,
  ...
} ]
```

**Comment by ChaelKruip** [comment]
> How about an action where you can request all scenarios with a particular preset_scenario_id? 

I like that!

**Comment by grdw** [comment]
Sounds good :) 

How about user specific scenario's?

**Comment by antw** [comment]
> How about user specific scenario's?

Sadly I think this is going to be a real pain; ETEngine does not (and should not) store authorship information.

If we want to get the scenarios saved by a particular ETModel user, I think we'll have to request those from the ETM (see [SavedScenario](https://github.com/quintel/etmodel/blob/9755db9a64d3623b5a67226c664caf9e819655e8/app/models/saved_scenario.rb)) and *then* go to ETEngine for the details. There is no ETModel action for this, so that will also have to be added. :persevere:

**Comment by grdw** [comment]
Let's just stick to the descendants approach. I think that's fine for now, @ChaelKruip ?

**Comment by dennisschoenmakers** [comment]
> If we want to get the scenarios saved by a particular ETModel user, I think we'll have to request those from the ETM (see SavedScenario) and then go to ETEngine for the details. There is no ETModel action for this, so that will also have to be added. :persevere:

We could also use the 'author' field of the Etengine scenarios. If Etmodel sends that of to Etengine (e.g. dennis.schoenmakers@quintel.com or the user_id, we could pick that up. Right? :smiley:

**Comment by antw** [comment]
> We could also use the 'author' field of the Etengine scenarios.

There's a `user_id` field, but that relates to the ETEngine user – and most scenarios have no value for that column.

Unless this feature is absolutely critical to the client, sending a user ID (or e-mail) to ETEngine is something I'd rather we didn't do. ETEngine doesn't care about this information, and we'd be (mis-)using it as a broker: "here's some unrelated attribute wanted by another application". I really dislike making changes to ETEngine for the sake of only one project or client as it makes future refactoring (or rewrites!) harder – it's one *more* feature which has to be included in a new ETE and, therefore, one more barrier to that ever happening. :wink:

If we must go this route, I'd prefer we add a generic JSON/YAML "metadata" column for other applications to send other data relevant to the scenario. But this isn't a great solution either since we can't use a serialised column in a `WHERE` clause. [Unless...](http://www.postgresql.org/docs/9.3/static/functions-json.html) :trollface:

Also: What if someone signs up to ETModel and ETLoader with different e-mail accounts? There'd be no way to tell it was the same person.

As much as I'd love to switch to Postgres, this whole issue feels like a hacky way around [having to implement CAS](https://github.com/quintel/etloader/issues/70#issuecomment-94417031).

Can we maybe leave user scenarios for now, and if it turns out to be *really* necessary, do it properly with CAS or some other single-sign-on system?

**Comment by dennisschoenmakers** [comment]
> As much as I'd love to switch to Postgres, this whole issue feels like a hacky way around having to implement CAS.

I get more and more the feeling we need to have a collective sign-in functionality, and a collective ownership structure for scenarios and 'testing grounds'. 

I suggest we start with this *after* the (TKI) workshop.

**Comment by ChaelKruip** [comment]
> I get more and more the feeling we need to have a collective sign-in functionality, and a collective ownership structure for scenarios and 'testing grounds'.

>I suggest we start with this after the (TKI) workshop.

:+1:

**Comment by grdw** [comment]
Closing this issue - already was able to get the title of a scenario when you go to: http://ivy.et-engine.com/testing_grounds/import?scenario_id=123
