### ISSUE TITLE
Can we use one profile for EV whether it is allowed to discharge or not?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#97]
I have the feeling that we could use the same profile whether EVs are allowed to give electricity back to the grid or not. Perhaps we could have a 'flag' that tells us if an EV can discharge @antw? 

To be clear: If we use neither demand shifting or storage, the EV should be using the fixed load profiles that we use now.

**Comment by antw** [comment]
I'm not sure what exactly is being asked.

If you want to say that a specific EV may not discharge, then I think it would behave like any other consumption technology. It would draw from the network however much energy the minimum load profile specifies. It wouldn't store *excess* energy from the network since it could never discharge it. This would be true regardless of whether you disable storage for that one EV, or the entire testing ground.

--

What's tripping me up is the word "grid" in this sentence:

> we could use the same profile whether EVs are allowed to give electricity back to the grid or not

As currently implemented, when storage is enabled, stored energy is never returned to the *grid* (represented as a negative load on the top-most node). It remains stored until there is a deficit of production in the testing ground, and is then discharged to meet demand.

Energy is only returned to the grid when there is an excess of production, *and* there is insufficient storage remaining to keep that excess within the testing ground for later use.

**Comment by ChaelKruip** [comment]
> I'm not sure what exactly is being asked.

Sorry for not being clearer! I'll Skype you tomorrow about this because I think it will be easier to explain verbally what I mean :smile:

**Comment by ChaelKruip** [comment]
This issue is superseded by the hopefully clearer https://github.com/quintel/etloader/issues/118
